"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '49d04f5bfe7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 第一步: 添加username列(允许NULL)
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'))
    
    # 第二步: 为现有用户生成默认username (使用phone作为默认值)
    op.execute("UPDATE users SET username = CONCAT('user_', phone) WHERE username IS NULL")
    
    # 第三步: 将username改为非NULL
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               nullable=False,
               existing_comment='用户名')
    
    # 第四步: 创建唯一索引
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # 第五步: 将name改为允许NULL
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_comment='用户姓名')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_comment='用户姓名')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
